
name: Generate Metrics

on:
  schedule: # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows you to run the workflow manually
  push: # Runs every time a commit is pushed to the main branch
    branches:
      - master

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, footer
          plugins: languages, stars, contributions, streak, commits
          user: elfaz2 # Replace with your GitHub username
